name: Build and Deploy Notebook Selective

on:
  push:
    paths:
      - 'Notebook/**'
  workflow_dispatch:
    inputs:
      notebook_filename:
        description: 'Filename of the notebook to deploy'
        required: true
        type: choice
        options: 
          - 'all'
          - 'sample-1.ipynb'
          - 'sample-2.ipynb'
          - 'sample-3.ipynb'
        default: 'sample-1.ipynb'

permissions:
  contents: write       # required for pushing back to QA or deploying

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package Notebook
        run: |
          mkdir -p build
          cp -R Notebook/* build/

      - name: Upload Notebook Artifact
        uses: actions/upload-artifact@v3
        with:
          name: notebook-artifact
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Notebook Artifact
        uses: actions/download-artifact@v3
        with:
          name: notebook-artifact

      - name: Debug Input
        run: |
          echo "Notebook filename: ${{ github.event.inputs.notebook_filename }}"

      - name: Set Notebook Path
        id: set-path
        run: |
          NOTEBOOK_FILENAME="${{ github.event.inputs.notebook_filename }}"
          if [ "$NOTEBOOK_FILENAME" = "all" ]; then
            NOTEBOOK_PATH="Notebook/"
          else
            NOTEBOOK_PATH="Notebook/$NOTEBOOK_FILENAME"
          fi
          echo "NOTEBOOK_PATH=$NOTEBOOK_PATH" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: |
          pip install --upgrade pip
          pip install databricks-cli

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databricks/config
          [DEFAULT]
          host = $DATABRICKS_HOST
          token = $DATABRICKS_TOKEN
          EOF

      - name: Deploy Notebook to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_WORKSPACE_DIR: '/Workspace/KrgProject'
        run: |
          if [ "${{ github.event.inputs.notebook_filename }}" = "all" ]; then
            for nb in Notebook/*.ipynb; do
              echo "Deploying $nb"
              databricks workspace import --overwrite "$nb" "$DATABRICKS_WORKSPACE_DIR/$(basename "$nb")" -l PYTHON
            done
          else
            nb="Notebook/${{ github.event.inputs.notebook_filename }}"
            echo "Deploying $nb"
            databricks workspace import --overwrite "$nb" "$DATABRICKS_WORKSPACE_DIR/$(basename "$nb")" -l PYTHON
          fi
